language: none

env:
  global:
    - SLEEP_DUR=5

matrix:
  include:
    - env: NAME=foo
    - env: NAME=bar
    - go: 1.11

build:
  # See: http://docs.shippable.com/ci/custom-docker-image/#minimum-requirements
  # pre_ci_boot:
  #   image_name: some_image
  #   image_tag: latest
  #   pull: true
  ci:
    # Docker artifacts are cached across all builds
    - docker build . --build-arg NAME=${NAME} --build-arg SLEEP_DUR=${SLEEP_DUR}
    # Try build Go project
    - cd ${GOPATH}
    - go get -v github.com/gruntwork-io/terragrunt
    - cd src/github.com/gruntwork-io/terragrunt
    - go build -v
  cache: true

jobs:
  - name: build-runCI
    type: runCI

branches:
  only:
    - master
