language: go

env:
  global:
    - SLEEP_DUR=5

matrix:
  include:
    - env: NAME=foo
    - env: NAME=bar
    - go:
      - 1.11

build:
  # See: http://docs.shippable.com/ci/custom-docker-image/#minimum-requirements
  # pre_ci_boot:
  #   image_name: some_image
  #   image_tag: latest
  #   pull: true
  ci:
    # Docker artifacts are cached across all builds
    - |-
      if ! which go > /dev/null; then
        docker build . --build-arg NAME=${NAME} --build-arg SLEEP_DUR=${SLEEP_DUR}
      fi
    # Try build Go project
    - |-
      if which go > /dev/null; then
        cd ${GOPATH}
        go get -v github.com/gruntwork-io/terragrunt
        cd src/github.com/gruntwork-io/terragrunt
        go build -v ./...
      fi
  cache: true

jobs:
  - name: build-runCI
    type: runCI

branches:
  only:
    - master
